In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Print all outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

We consider a stock price at a given point in time as a vector

$$x_i = \begin{pmatrix}
    low \\ 
    high \\ 
    open \\ 
    close \\
    vwap \\
    volume
\end{pmatrix}$$

And a collection of historical prices for a stock as a matrix

$$\bf{x} = \begin{pmatrix}
    x_0^T \\ 
    x_1^T \\
    . \\
    . \\
    . \\
    x_n^T
\end{pmatrix}
=
\begin{pmatrix}
    low(x_0) & high(x_0) & open(x_0) & close(x_0) & vwap(x_0) & volume(x_0) \\
    low(x_1) & high(x_1) & open(x_1) & close(x_1) & vwap(x_1) & volume(x_1) \\
    . & . & . & . & . & . \\
    low(x_n) & high(x_n) & open(x_n) & close(x_n) & vwap(x_n) & volume(x_n) \\
\end{pmatrix}
$$

Firstly, this keeps all data well organized and contained within a single object. Secondly, it allows for studies to be described in the context of linear algebra operations.

For instance, the computation of $$(high + low + open + close) / 4$$ can be described as

$$\frac{(high + low + open + close)}{4} = \bf{x} \cdot \frac{1}{4} \begin{pmatrix}
  1 \\
  1 \\
  1 \\
  1 \\
  0 \\
  0
\end{pmatrix}
$$

In [2]:
# Compute (high + low + open + close) / 4 using matrix operations
data = np.arange(0, 36).reshape(6,6)
hloc = np.array([1, 1, 1, 1, 0, 0]).reshape(6, 1) / 4

data
hloc
data @ hloc



array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

array([[0.25],
       [0.25],
       [0.25],
       [0.25],
       [0.  ],
       [0.  ]])

array([[ 1.5],
       [ 7.5],
       [13.5],
       [19.5],
       [25.5],
       [31.5]])

In this case we can compute the desired result through matrix operations rather than having to write a complicated algorithm. 

We also have the flexibility to apply an operation to multiple features of a price history at once. Suppose that we want to compute a gradient to analyze changes in each price feature over time. We can compute a single gradient that will be valid for each feature.

In [3]:
np.gradient(data, axis=0)

array([[6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.]])

## Moving Averages

We can describe the n period simple moving average and exponential moving average as matrix operators

## Divergence

We can easily determine correlations between past prices and study values to search for divergences between the study and price during future trading. Assuming that the input data is a N by 6 matrix, the transform must have dimensions 6xN


In [111]:
data = np.arange(0, 42).reshape(7,6)
data
shape = data.shape[::-1]
sma = np.ones(shape) - np.tri(shape[0], M=shape[-1], k=-1)
sma

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

array([[1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1.]])

In [4]:
data = np.arange(0, 36*3, 3).reshape(6,6)
study = data
data = data * 2
study[3, 0] = 58
div = np.diff(data, axis=0) / np.diff(study, axis=0)

data
study
div
np.mean(div, axis=0)
np.std(div, axis=0)

array([[  0,   6,  12,  18,  24,  30],
       [ 36,  42,  48,  54,  60,  66],
       [ 72,  78,  84,  90,  96, 102],
       [108, 114, 120, 126, 132, 138],
       [144, 150, 156, 162, 168, 174],
       [180, 186, 192, 198, 204, 210]])

array([[  0,   3,   6,   9,  12,  15],
       [ 18,  21,  24,  27,  30,  33],
       [ 36,  39,  42,  45,  48,  51],
       [ 58,  57,  60,  63,  66,  69],
       [ 72,  75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102, 105]])

array([[2.        , 2.        , 2.        , 2.        , 2.        ,
        2.        ],
       [2.        , 2.        , 2.        , 2.        , 2.        ,
        2.        ],
       [1.63636364, 2.        , 2.        , 2.        , 2.        ,
        2.        ],
       [2.57142857, 2.        , 2.        , 2.        , 2.        ,
        2.        ],
       [2.        , 2.        , 2.        , 2.        , 2.        ,
        2.        ]])

array([2.04155844, 2.        , 2.        , 2.        , 2.        ,
       2.        ])

array([0.30004216, 0.        , 0.        , 0.        , 0.        ,
       0.        ])

The resultant array tells us that on average a two fold increase in the value of a study should be associated with a four fold increase in price. We can apply this to future values of the study and price to note when the two diverge. Divergence of price and study trends may indicate that the price trend is nearing a reversal

## Pandas

We can use pandas to effectively managed labeled data. Extraction of Numpy arrays from data frames is simple

In [51]:
import pandas as pd
import plotly.plotly as py
import plotly.graph_objs as go
from datetime import datetime

df = pd.read_json('/home/tidal/Dropbox/Software/trader/data/aapl-1d1m.json')
df

average  changeOverTime    close      date     high     label      low  \
0    229.278        0.000000  229.510  20180905  229.510  09:30 AM  228.940   
1    229.549        0.001182  229.420  20180905  229.615  09:31 AM  229.420   
2    229.065       -0.000929  229.020  20180905  229.340  09:32 AM  228.970   
3    228.895       -0.001670  228.770  20180905  229.070  09:33 AM  228.700   
4    228.576       -0.003062  228.460  20180905  228.775  09:34 AM  228.460   
5    228.770       -0.002216  229.060  20180905  229.070  09:35 AM  228.480   
6    228.843       -0.001897  228.730  20180905  229.070  09:36 AM  228.690   
7    228.639       -0.002787  228.550  20180905  228.890  09:37 AM  228.420   
8    228.536       -0.003236  228.420  20180905  228.660  09:38 AM  228.420   
9    228.528       -0.003271  228.490  20180905  228.610  09:39 AM  228.400   
10   228.311       -0.004218  228.090  20180905  228.480  09:40 AM  227.995   
11   228.279       -0.004357  228.330  20180905  228.400  09:41 AM  228.125   
12   228.397       -0.003842  228.450  20180905  228.530  09:42 AM  228.260   
13   228.443       -0.003642  228.490  20180905  228.520  09:43 AM  228.320   
14   228.647       -0.002752  228.610  20180905  228.770  09:44 AM  228.510   
15   228.655       -0.002717  228.720  20180905  228.840  09:45 AM  228.570   
16   228.693       -0.002551  228.645  20180905  228.800  09:46 AM  228.580   
17   228.687       -0.002578  228.680  20180905  228.740  09:47 AM  228.630   
18   228.436       -0.003672  228.240  20180905  228.660  09:48 AM  228.220   
19   228.302       -0.004257  228.420  20180905  228.450  09:49 AM  228.200   
20   228.254       -0.004466  228.200  20180905  228.470  09:50 AM  228.120   
21   228.277       -0.004366  228.150  20180905  228.340  09:51 AM  228.150   
22   227.925       -0.005901  227.730  20180905  228.170  09:52 AM  227.730   
23   227.751       -0.006660  227.660  20180905  227.830  09:53 AM  227.660   
24   227.703       -0.006869  227.750  20180905  227.750  09:54 AM  227.650   
25   227.580       -0.007406  227.500  20180905  227.650  09:55 AM  227.480   
26   227.316       -0.008557  227.310  20180905  227.530  09:56 AM  227.200   
27   227.173       -0.009181  227.070  20180905  227.370  09:57 AM  226.990   
28   226.957       -0.010123  226.850  20180905  227.060  09:58 AM  226.850   
29   226.665       -0.011397  226.410  20180905  226.840  09:59 AM  226.410   
..       ...             ...      ...       ...      ...       ...      ...   
360  227.083       -0.009574  227.080  20180905  227.140   3:30 PM  227.030   
361  227.062       -0.009665  226.990  20180905  227.140   3:31 PM  226.990   
362  227.026       -0.009822  226.980  20180905  227.060   3:32 PM  226.930   
363  227.062       -0.009665  227.060  20180905  227.130   3:33 PM  226.985   
364  227.107       -0.009469  227.100  20180905  227.170   3:34 PM  227.060   
365  227.066       -0.009648  227.070  20180905  227.130   3:35 PM  227.030   
366  226.986       -0.009997  226.930  20180905  227.060   3:36 PM  226.910   
367  226.843       -0.010620  226.790  20180905  226.940   3:37 PM  226.770   
368  226.746       -0.011043  226.730  20180905  226.810   3:38 PM  226.690   
369  226.807       -0.010777  226.890  20180905  226.890   3:39 PM  226.710   
370  226.671       -0.011370  226.595  20180905  226.845   3:40 PM  226.580   
371  226.593       -0.011711  226.645  20180905  226.645   3:41 PM  226.530   
372  226.738       -0.011078  226.760  20180905  226.790   3:42 PM  226.650   
373  226.729       -0.011118  226.650  20180905  226.790   3:43 PM  226.640   
374  226.592       -0.011715  226.550  20180905  226.670   3:44 PM  226.530   
375  226.478       -0.012212  226.480  20180905  226.520   3:45 PM  226.445   
376  226.532       -0.011977  226.550  20180905  226.560   3:46 PM  226.480   
377  226.585       -0.011746  226.480  20180905  226.710   3:47 PM  226.480   
378  226.457       -0.012304  226.455  20180905  226.55

In [6]:
df.close

0      229.510
1      229.420
2      229.020
3      228.770
4      228.460
5      229.060
6      228.730
7      228.550
8      228.420
9      228.490
10     228.090
11     228.330
12     228.450
13     228.490
14     228.610
15     228.720
16     228.645
17     228.680
18     228.240
19     228.420
20     228.200
21     228.150
22     227.730
23     227.660
24     227.750
25     227.500
26     227.310
27     227.070
28     226.850
29     226.410
        ...   
360    227.080
361    226.990
362    226.980
363    227.060
364    227.100
365    227.070
366    226.930
367    226.790
368    226.730
369    226.890
370    226.595
371    226.645
372    226.760
373    226.650
374    226.550
375    226.480
376    226.550
377    226.480
378    226.455
379    226.300
380    226.360
381    226.340
382    226.470
383    226.360
384    226.350
385    226.460
386    226.540
387    226.530
388    226.640
389    226.710
Name: close, Length: 390, dtype: float64

In [52]:
trace = go.Candlestick(x=df.label.values,
                       open=df.open.values,
                       high=df.high.values,
                       low=df.low.values,
                       close=df.close.values)
data = [trace]
py.iplot(data)

Aw, snap! We didn't get a username with your request.

Don't have an account? https://plot.ly/api_signup

Questions? accounts@plot.ly


PlotlyError: Because you didn't supply a 'file_id' in the call, we're assuming you're trying to snag a figure from a url. You supplied the url, '', we expected it to start with 'https://plot.ly'.
Run help on this function for more information.

Data selected from Pandas dataframes as numpy arrays can be operated on

In [8]:
close = df.close.values


## Support and Resistance

We can use peak detection algorithms to identify support and resistance levels

In [101]:
import numpy as np
import scipy.signal as sig
import mpl_finance as fin

plt.rcParams["figure.figsize"] = (15,10)

x = np.arange(0, len(close))
r = np.arange(1, 10)
h = 228


highs = sig.find_peaks_cwt(df.high.values, r)
lows = sig.find_peaks_cwt(df.low.values*-1, r)

ax = plt.subplot()
plt.plot(x[lows], df.low.values[lows], linestyle='none', marker='o', markerfacecolor='b')
plt.plot(x[highs], df.high.values[highs], linestyle='none', marker='o', markerfacecolor='k')
fin.candlestick2_ohlc(ax, df.open.values, df.high.values, df.low.values, df.close.values, width=1, 
                      colorup='g', colordown='r', alpha=0.75)
plt.xlim([200, 400])
plt.show()

/usr/lib/python3.7/site-packages/scipy/stats/stats.py:1713: FutureWarning:

Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.



(<matplotlib.collections.LineCollection at 0x7fc814888550>,
 <matplotlib.collections.PolyCollection at 0x7fc8148886a0>)

(200, 400)